name: amaan_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  audioplayers: ^5.2.1
  lottie: ^3.3.3
  google_fonts: ^8.0.2
  supabase_flutter: ^2.5.6   
  shared_preferences: ^2.5.5
  geolocator: ^14.0.2
  permission_handler: ^12.0.3
  firebase_core: ^4.10.0
  firebase_messaging: ^16.3.0
  record: ^6.2.1
  path_provider: ^2.1.5
  flutter_send_sms: ^1.0.1
  just_audio: ^0.10.5
  flutter_foreground_task: ^9.2.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/click.mp3
    - assets/shield.json
    - assets/google.png
    - assets/facebook.png

